-- CREATE DATABASE IF NOT EXISTS streamingdb; -- Remove this line if creating the DB externally (e.g. via Docker / psql)
-- -- \c streamingdb  -- Uncomment if running via psql to switch into the new DB
-- Docker-Compose already defined the DB. Don't have to use CREATE DATABASE unless you are running it on the IDE itself.

-- ============================================================
-- STRONG & FULLY INDEPENDENT ENTITIES
-- ============================================================

-- Changed SERIAL to GENERATED BY DEFAULT AS IDENTITY (Ensure that the users don't manually added the ID)
-- Changed TIMESTAMP to TIMESTAMPTZ to also store the timezone

CREATE TABLE IF NOT EXISTS membership_tier (
    tier_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tier_name    VARCHAR(50)    NOT NULL UNIQUE,  -- e.g. 'free', 'premium', 'admin'
    monthly_price NUMERIC(10, 2) NOT NULL,
    discount_rate NUMERIC(3, 2), -- e.g. 0.20 for 20%
    duration_days INT           NOT NULL,          -- e.g. -1, 30, 365, etc.
    description  TEXT,

    CONSTRAINT valid_tier_price CHECK (monthly_price >= 0.00)
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS language_list (
    language_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_name   VARCHAR(100) NOT NULL UNIQUE,
    native_name     VARCHAR(100) NOT NULL -- native name such as ไทย
);

CREATE TABLE IF NOT EXISTS timezone (
    timezone_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iana_name       VARCHAR(50)  NOT NULL UNIQUE,  -- e.g. 'Asia/Bangkok'
    current_offset  VARCHAR(10)  NOT NULL,         -- e.g. '+07:00'
    abbreviation    VARCHAR(10)  NOT NULL          -- e.g. 'ICT'
);

CREATE TABLE IF NOT EXISTS content_rating (
    rating_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating_label        VARCHAR(10) NOT NULL UNIQUE,
    maturity_level      INT     NOT NULL,            -- age e.g. 16, 18, 20
    rating_description  TEXT
);

-- ============================================================
-- STRONG BUT USING REFERENCES
-- ============================================================
CREATE TABLE IF NOT EXISTS country (
    country_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name        VARCHAR(100) NOT NULL UNIQUE,
    country_code        VARCHAR(10) NOT NULL, -- TH, CN, etc.
    primary_timezone_id INT,
    FOREIGN KEY (primary_timezone_id) REFERENCES timezone(timezone_id)
);

CREATE TABLE IF NOT EXISTS app_user (
    user_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50)  NOT NULL UNIQUE,
    email           VARCHAR(255) NOT NULL UNIQUE,
    img_path        VARCHAR(150),
    user_password   VARCHAR(255) NOT NULL,
    register_date   TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    country_id      INT,
    tier_id         INT          NOT NULL REFERENCES membership_tier(tier_id),  -- replaces user_type
    user_status     VARCHAR(50)  NOT NULL CHECK (user_status IN ('active', 'suspended', 'banned')),
    user_role     VARCHAR(20)  DEFAULT 'customer' CHECK (user_role IN ('admin', 'customer')),

    FOREIGN KEY (country_id) REFERENCES country(country_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS person (
    person_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    img_path    VARCHAR(150), -- poster image path
    first_name  VARCHAR(100) NOT NULL, 
    middle_name VARCHAR(100),
    last_name   VARCHAR(100) NOT NULL,
    nationality VARCHAR(100) NOT NULL,
    birth_date  DATE NOT NULL,
    birth_place VARCHAR(100) NOT NULL,
    biography   TEXT,
    create_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, -- the time that this person is added
    update_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, -- the time that this person is modified
    create_by   INT NOT NULL REFERENCES app_user(user_id), -- added by who?
    update_by   INT REFERENCES app_user(user_id) -- modified by who?
);

CREATE TABLE IF NOT EXISTS content (
    content_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(255) NOT NULL,
    img_path    VARCHAR(150), -- poster image path
    content_description TEXT,
    release_date        DATE,
    price               NUMERIC(10, 2) NOT NULL DEFAULT 0.0,
    content_type        VARCHAR(50)  NOT NULL CHECK (content_type IN ('Movie', 'TV Show')),
    rating_id           INT          NOT NULL,
    country_id          INT,
    create_date         TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    update_date         TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP, -- the date when the content is added and updated
    create_by           INT REFERENCES app_user(user_id),
    update_by           INT          NOT NULL REFERENCES app_user(user_id), -- added or updated by who?

    CONSTRAINT valid_content_price CHECK (price >= 0.0),
    FOREIGN KEY (rating_id)  REFERENCES content_rating(rating_id),
    FOREIGN KEY (country_id) REFERENCES country(country_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS transaction_list (
    transaction_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             INT,                                    -- Nullable: ON DELETE SET NULL
    transaction_date    TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount        NUMERIC(10, 3) NOT NULL DEFAULT 0.0,
    payment_method VARCHAR(100) NOT NULL CHECK (payment_method IN ('credit_card', 'debit_card', 'paypal', 'bank_transfer')),
    payment_status VARCHAR(100) NOT NULL CHECK (payment_status IN ('Completed', 'Pending', 'Refunded', 'Cancelled')),

    FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE SET NULL,
    CONSTRAINT valid_transaction_price CHECK (total_amount >= 0.0)
);

CREATE TABLE IF NOT EXISTS transaction_detail (
    detail_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id INT        NOT NULL,
    content_id     INT,
    content_name   VARCHAR(255)   NOT NULL,  -- Retained even if content is deleted
    original_price   NUMERIC(10, 3),
    discount_applied NUMERIC(10, 3),
    sold_price     NUMERIC(10, 3) NOT NULL DEFAULT 0.0 CHECK (sold_price >= 0.0),

    FOREIGN KEY (transaction_id) REFERENCES transaction_list(transaction_id) ON DELETE CASCADE,
    FOREIGN KEY (content_id)     REFERENCES content(content_id)             ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS subscription_history (
    detail_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id INT         NOT NULL,
    tier_id        INT,
    tier_name      VARCHAR(50) NOT NULL,  -- Retained even if the tier is deleted
    start_date     DATE        NOT NULL,
    end_date    DATE NOT NULL CHECK (end_date > start_date),  -- prevents invalid date ranges
    sold_price  NUMERIC(10, 3) NOT NULL DEFAULT 0.0 CHECK (sold_price >= 0.0),

    FOREIGN KEY (transaction_id) REFERENCES transaction_list(transaction_id) ON DELETE CASCADE,
    FOREIGN KEY (tier_id)        REFERENCES membership_tier(tier_id)         ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS reviews (
    review_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INT,
    content_id      INT        NOT NULL,
    rating          NUMERIC(2, 1)  NOT NULL,
    comment_text    TEXT,
    post_time       TIMESTAMPTZ      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    post_status     VARCHAR(100)     NOT NULL CHECK (post_status IN ('Published', 'Hidden', 'Removed')),

    UNIQUE (user_id, content_id),

    FOREIGN KEY (user_id)    REFERENCES app_user(user_id)   ON DELETE SET NULL,
    FOREIGN KEY (content_id) REFERENCES content(content_id) ON DELETE CASCADE,
    CONSTRAINT valid_rating CHECK (rating >= 1.0 AND rating <= 5.0)
);


-- ============================================================
-- WEAK & ASSOCIATIVE ENTITIES
-- ============================================================

-- ── Playlist ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS playlist (
    playlist_id   INT      NOT NULL,
    user_id       INT      NOT NULL,
    playlist_name VARCHAR(100) NOT NULL,
    create_date   TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    visibility    VARCHAR(100) NOT NULL CHECK (visibility IN ('Public', 'Unlisted', 'Hidden')),

    PRIMARY KEY (user_id, playlist_id),
    FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS playlist_item (
    playlist_id INT   NOT NULL,
    user_id     INT   NOT NULL,
    content_id  INT   NOT NULL,
    add_date    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (user_id, playlist_id, content_id),
    FOREIGN KEY (user_id, playlist_id) REFERENCES playlist(user_id, playlist_id) ON DELETE CASCADE,
    FOREIGN KEY (content_id)           REFERENCES content(content_id)           ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS personal_library (
    library_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INT,
    content_id    INT,
    purchase_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id) REFERENCES app_user(user_id) ON DELETE CASCADE,
    FOREIGN KEY (content_id) REFERENCES content(content_id) ON DELETE CASCADE
);

-- ── User Inventory ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_content (
    user_id      INT NOT NULL,
    content_id   INT NOT NULL,
    last_watch   TIMESTAMPTZ, -- can be null if the user hasn't watched it
    watch_status VARCHAR(100) CHECK (watch_status IN ('Unwatched', 'Unfinished', 'Finished')),

    PRIMARY KEY (user_id, content_id),
    FOREIGN KEY (user_id)    REFERENCES app_user(user_id)    ON DELETE CASCADE,
    FOREIGN KEY (content_id) REFERENCES content(content_id) ON DELETE CASCADE
);

-- ── Content Subclasses ────────────────────────────────────
CREATE TABLE IF NOT EXISTS tv_show (
    content_id   INT     PRIMARY KEY,
    curr_status  VARCHAR(100) NOT NULL CHECK (curr_status IN ('Not aired', 'Airing', 'Off')),

    FOREIGN KEY (content_id) REFERENCES content(content_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS movie (
    content_id INT PRIMARY KEY,
    curr_status  VARCHAR(100) NOT NULL CHECK (curr_status IN ('Unreleased', 'Released')),
    run_time   INT NOT NULL,  -- Minutes

    FOREIGN KEY (content_id) REFERENCES content(content_id) ON DELETE CASCADE
);

-- ── Seasons & Episodes ────────────────────────────────────
CREATE TABLE IF NOT EXISTS season (
    content_id  INT,
    season_num  INT,
    air_date    DATE NOT NULL,
    synopsis    TEXT,

    PRIMARY KEY (content_id, season_num),
    FOREIGN KEY (content_id) REFERENCES content(content_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS episode (
    content_id  INT,
    season_num  INT,
    episode_num INT,
    episode_id  INT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE, -- unique identifier (not used as a key)
    title       VARCHAR(150) NOT NULL,
    synopsis    TEXT,
    run_time    INT,  -- Minutes

    PRIMARY KEY (content_id, season_num, episode_num),
    FOREIGN KEY (content_id, season_num) REFERENCES season(content_id, season_num) ON DELETE CASCADE
);

-- ── Video Quality ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS media_path (
    source_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- unique ID for each file
    content_id INT NOT NULL,  -- links to the main 'content'
    episode_id INT,           -- can be null for movies, not null for series

    -- SD=480p, HD=720p, FHD=1080p 16:9, QHD=1440p, 2K=1080p 1:1.77, UHD=4K, FUHD=8K
    quality    VARCHAR(50)  NOT NULL CHECK (quality IN ('SD', 'HD', 'FHD', 'QHD', '2K', 'UHD', 'FUHD')),
    file_path  VARCHAR(255) NOT NULL,
    priority   INT NOT NULL DEFAULT 1,

    -- Foreign Keys
    FOREIGN KEY (content_id) REFERENCES content(content_id) ON DELETE CASCADE,
    FOREIGN KEY (episode_id) REFERENCES episode(episode_id) ON DELETE CASCADE,

    -- Logic Constraint: If it's a show, it MUST have an episode_id.
    -- (Requires content_type to be checked or handled in application logic)
    CONSTRAINT unique_media_version UNIQUE (content_id, episode_id, quality, priority)
);

-- ── Content Details ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS content_genre (
    content_id INT,
    genre_id   INT,

    PRIMARY KEY (content_id, genre_id),
    FOREIGN KEY (content_id) REFERENCES content(content_id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id)   REFERENCES genre(genre_id)     ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS content_role (
    content_id     INT,
    person_id      INT,
    role_type      VARCHAR(100) NOT NULL CHECK (role_type IN ('Actor', 'Director', 'Producer', 'Crew')),
    character_name VARCHAR(200),

    PRIMARY KEY (content_id, person_id),
    FOREIGN KEY (content_id) REFERENCES content(content_id) ON DELETE CASCADE,
    FOREIGN KEY (person_id)  REFERENCES person(person_id)   ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS content_resource (
    resource_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id  INT NOT NULL,
    episode_id  INT,           -- NULL for standalone Movies
    language_id INT NOT NULL,
    lang_type   VARCHAR(50) NOT NULL CHECK (lang_type IN ('Audio', 'Subtitle')),
    file_path   VARCHAR(255) NOT NULL,
    priority   INT NOT NULL DEFAULT 1,

    -- Foreign Keys
    FOREIGN KEY (content_id)  REFERENCES content(content_id) ON DELETE CASCADE,
    FOREIGN KEY (episode_id)  REFERENCES episode(episode_id) ON DELETE CASCADE,
    FOREIGN KEY (language_id) REFERENCES language_list(language_id) ON DELETE CASCADE,

    -- Logic Constraint: Prevents duplicate paths for the same version
    CONSTRAINT unique_resource_entry UNIQUE (content_id, episode_id, language_id, lang_type, priority)
);